services:
  - type: web
    name: railway-crowd-monitor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash render_start.sh
    plan: free
    region: singapore
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
